- name: "Install automount utility and filesytem-support libs"
  ansible.builtin.include_tasks: install/main.yml

- name: "Configure automount utility"
  ansible.builtin.include_tasks: configure/main.yml

